#!/bin/bash

# Script to align backplanes with physical enclosure, script custom made to specific chassis
# alter for use in your own chassis, align values in /sys/class/enclosure with positions/labels
# in physical space in data center for easy location

# Enclosure design, Supermicro 45 drive SAS II JBOD, stacked 1-2 bottom to top

enclosures=($(ls /sys/class/enclosure))
if [ $1 == "${enclosures[0]}" ]; then
	enclosure=1
	side=Front
elif [ $1 == "${enclosures[1]}" ]; then
	enclosure=1
	side=Back
elif [ $1 == "${enclosures[2]}" ]; then
	enclosure=2
	side=Front
elif [ $1 == "${enclosures[3]}" ]; then
	enclosure=2
	side=Back
else
	enclosure=error
	side=error
fi

echo Enclosure:$enclosure
echo Side: $side
bad=$(echo $2 | sed 's/^0*//')
for i in `seq 1 24`
         do
                 slot[$i]="  HEALTHY  "
         done
         slot[$bad]="      BAD      "


if [ $side == "Front" ]; then
echo "
|${slot[6]}|${slot[12]}|${slot[18]}|${slot[24]}|
|${slot[5]}|${slot[11]}|${slot[17]}|${slot[23]}|
|${slot[4]}|${slot[10]}|${slot[16]}|${slot[22]}|
|${slot[3]}|${slot[9]}|${slot[15]}|${slot[21]}|
|${slot[2]}|${slot[8]}|${slot[14]}|${slot[20]}|
|${slot[1]}|${slot[7]}|${slot[13]}|${slot[19]}|"
elif [ $side == "Back" ]; then
#Check on back mapping
echo "
|   EMPTY   |${slot[9]}|${slot[15]}|${slot[21]}|
|   EMPTY   |${slot[8]}|${slot[14]}|${slot[20]}|
|   EMPTY   |${slot[7]}|${slot[13]}|${slot[19]}|
|${slot[3]}|${slot[6]}|${slot[12]}|${slot[18]}|
|${slot[2]}|${slot[5]}|${slot[11]}|${slot[17]}|
|${slot[1]}|${slot[4]}|${slot[10]}|${slot[16]}|"
else
	echo "Error Drawing Array"
fi
