#!/bin/bash

# Custmomize Based on Enclosure
# Enclosure design, Supermicro 45 drive SAS II JBOD

enclosures=$(ls /sys/class/enclosure/ | grep "1:")
#Number of backplanes per physical enclosure
perchassis=2
count=0
#Starting Enclosure Number
enclosure_num=1

echo "multipath		no" > /etc/zfs/vdev_id.conf
echo "topology		sas_direct" >> /etc/zfs/vdev_id.conf
echo "" >> /etc/vd_id.conf

for e in ${enclosures[@]}
do
	if [ $count -lt $perchassis ]; then
		echo leave number > /dev/null
	else
		enclosure_num=$((enclosure_num+1))
		count=0
	fi
	numslots=$(cat /sys/class/enclosure/$e/components)
	if [ $numslots -eq 24 ]; then
		side=F
	else
		side=B
	fi
	for s in `seq -w $numslots`
	do
		installed=$(cat /sys/class/enclosure/$e/"Slot $s"/status)
		if [ "$installed" == "not installed" ]; then
			echo Empty > /dev/null
		else
			dev=$(ls /sys/class/enclosure/$e/"Slot $s"/device/block/)
			path=$(udevadm info --query=property /dev/$dev | grep ID_PATH= | cut -d"=" -f2)
			id="/dev/disk/by-path/$path"
			printf "alias \t En"$enclosure_num"_Si"$side"_Sl"$s" \t "$id >> /etc/zfs/vdev_id.conf
			echo "" >> /etc/zfs/vdev_id.conf
		fi
	done
	count=$((count+1))
done
udevadm trigger
